### ISSUE TITLE
Have the bot receive all messages even when it is busy in the room

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#67] opened 2015-02-23 19:53 UTC
Once in a while the bot misses an message for unknown reasons but this happens if there are multiple messages in quick succession.

**Comment by gunr2171** [comment] 2015-02-23 19:58
_sigh_, I knew this would be written up at some point.

If the reason is the bot's code then it's most likely because of the multithreading. @ArcticEcho recently updated the CE.Net library to possibly eliminate / reduce that issue. That code is now incorporated into PR #66 and I'm working to finish it up (all that is left is to fix the CE.Net url).

So theoretically that should fix the problem.

Also, as a good test, I want to checkout a copy of CE.Net's example project and have two people write messages within a second of each other. If the example project can handle it then we know where the problem is.

And if not, well, more digging...

**Comment by rschrieken** [comment] 2015-02-23 20:03
Is there a reliable testcase?

**Comment by gunr2171** [comment] 2015-02-23 20:05
The example project in CE.Net. I have no idea how reliable it is (cc @ArcticEcho). That's the only thing I know for testing purposes.

Though sam has told me before that he hasn't had these types of problems with Pham, leading me to believe it's the `async`.

**Comment by ArcticEcho** [comment] 2015-02-27 17:14
Erm, CE.Net's issue on thread safety is still active and I haven't actually go round to committing anything, yet. The example project doesn't use any parallelisation, therefore it's useless in this case as a test.

**Comment by gunr2171** [comment] 2015-02-27 17:18
Yeah, I noticed that [later](http://chat.stackoverflow.com/transcript/message/21804842#21804842). Oh well.

The reason I wanted to use the example project, which I know is _not_ asynchronous, was to test if that was in fact the reason.

**Comment by rschrieken** [comment] 2015-03-26 22:02
anyway: here is a testscript 

    (function () { var a = ['commands','help','status', 'alive','running commands'], i = window.setInterval(function() { var c = a.shift(); if (c === undefined) { window.clearInterval(i); } else {  $('#input').val('@KennyBot ' + c ); $('#sayit-button').click(); }}, 5000); })();

and I'll push a brach with a possible fix but that might need some extra discussion before merge in main

**Comment by ArcticEcho** [comment] 2015-04-21 08:38
Is this bug still active?

**Comment by gunr2171** [comment] 2015-04-21 12:34
@ArcticEcho, it's been on a sort of break. Rene did make that branch but I haven't got around to testing it yet.

However, since we fixed the "cache the Content of a message" the bot has become a lot more stable, only dropping messages every 3 days or so.

So it's still an issue, but it's better than before.

**Comment by ArcticEcho** [comment] 2015-04-21 12:41
Oh, I see.

**Comment by gunr2171** [comment] 2015-05-01 21:51
As an update, since we've moved to the linux version I've noticed _one_ message in ~5 days get missed by the bot.

**Comment by ArcticEcho** [comment] 2015-05-01 21:53
Can you confirm that it's not caused by a collision?

**Comment by gunr2171** [comment] 2015-05-01 21:55
[Here was the chat message it came from](http://chat.stackoverflow.com/transcript/message/23046796#23046796). I'm not entirely sure, but I think it was caused by a collision.

(And because I just remembered) [Shortly after](http://chat.stackoverflow.com/transcript/message/23046825#23046825) it missed a message of mine, but it was _absolutly_ caused by a collision.

**Comment by rschrieken** [comment] 2015-05-15 10:10
Just realize that the bot will miss messages as long as  [this line](https://github.com/ArcticEcho/ChatExchange.Net/blob/master/ChatExchange.Net/Room.cs#L649) is not fixed. That is an array, that **CAN** contain more items (it only has one item most of the time). Currently only the first message is handled, the rest is discarded

**Comment by ArcticEcho** [comment] 2015-05-15 13:00
Ah, my bad. I assumed only one chat message was sent per socket message. I'll fix this asap.

**Comment by ArcticEcho** [comment] 2015-05-15 17:14
All fixed as of 2.1.9-beta.

**Comment by ArcticEcho** [comment] 2015-06-06 18:43
Closing this issue upon further testing/discussion.

> Sam: [I forgot @rene, have we actually concluded that Closey's message missing bug has been fixed yet?](http://chat.stackoverflow.com/transcript/message/23732207#23732207)

> Rene: [@Sam yeah, let's close it and open a new one if it reappears](http://chat.stackoverflow.com/transcript/message/23732250#23732250)
> [much has changed so that invalidates the bug anyway](http://chat.stackoverflow.com/transcript/message/23732257#23732257)

**Closed by ArcticEcho** 2015-06-06 18:43 UTC
Labels: bug, high-priority
